;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="CreatureDied",NewTagName="Creature")
+GameplayTagRedirects=(OldTagName="Creature.Genus",NewTagName="Creature.Family")
+GameplayTagRedirects=(OldTagName="Creature.Family.Friendly",NewTagName="Creature.Family.Person")
+GameplayTagRedirects=(OldTagName="Creature.Emotion.Hapy",NewTagName="Creature.Emotion.Happy")
+GameplayTagList=(Tag="Creature",DevComment="")
+GameplayTagList=(Tag="Creature.Alive",DevComment="")
+GameplayTagList=(Tag="Creature.Alive.Idle",DevComment="")
+GameplayTagList=(Tag="Creature.Alive.Moving",DevComment="")
+GameplayTagList=(Tag="Creature.Died",DevComment="")
+GameplayTagList=(Tag="Creature.Died.Gibbed",DevComment="")
+GameplayTagList=(Tag="Creature.Emotion",DevComment="")
+GameplayTagList=(Tag="Creature.Emotion.Angry",DevComment="")
+GameplayTagList=(Tag="Creature.Emotion.Curious",DevComment="")
+GameplayTagList=(Tag="Creature.Emotion.Happy",DevComment="")
+GameplayTagList=(Tag="Creature.Emotion.Refresh",DevComment="")
+GameplayTagList=(Tag="Creature.Emotion.Sad",DevComment="")
+GameplayTagList=(Tag="Creature.Emotion.Scared",DevComment="")
+GameplayTagList=(Tag="Creature.Family",DevComment="")
+GameplayTagList=(Tag="Creature.Family.Animal",DevComment="")
+GameplayTagList=(Tag="Creature.Family.BadGuy",DevComment="")
+GameplayTagList=(Tag="Creature.Family.Person",DevComment="")
+GameplayTagList=(Tag="Creature.Move",DevComment="")
+GameplayTagList=(Tag="Creature.Move.Reset",DevComment="")
+GameplayTagList=(Tag="Creature.Move.Teleport",DevComment="")
+GameplayTagList=(Tag="Creature.Revive",DevComment="")
+GameplayTagList=(Tag="player.attack",DevComment="")
+GameplayTagList=(Tag="player.crouch",DevComment="")
+GameplayTagList=(Tag="player.jump",DevComment="")
+GameplayTagList=(Tag="player.kick",DevComment="")

